### ISSUE TITLE
Network Problems

### ISSUE THREAD

**Issue by dyingphoenix** [getminera/minera#186] opened 2017-11-03 13:17 UTC
Hi,

got a raspberry pi3 with actual firmware (upgraded before), and using the actual minera image (0.8.1). When starting up I don't get an IP adress, only loopback is active; are there any known issues about this? Using the builtin eth0 of the raspberry.

**Comment by dyingphoenix** [comment] 2017-11-03 14:31
Tried now with Raspian as base. System works well, but when using the manual install script (curl -o- https://raw.githubusercontent.com/michelem09/minera/master/install_minera_ubuntu.sh | sudo bash) after next reboot the raspberry is no more reachable via network.
And it's neither the raspberry nor Raspian, for I rebooted some more times before installing minera.

**Comment by michelem09** [comment] 2017-11-03 14:40
this is weird and I should try my own side, but did you try to start from the Minera image here https://getminera.com/download/latest ?
I'd like to know your feedback so I can investigate in the manual install only.
Thanks

**Comment by dyingphoenix** [comment] 2017-11-03 14:43
Yes, first thing I tried was using the image, got it to work, but never got any ip address (have checked this twice) and then I tried to use the manual install from https://github.com/getminera/minera/wiki/Getting-started to get it to work, system worked as said (pure Raspian, Image 2017-09-07-raspbian-stretch-lite.img) until installing Minera and rebooting.

**Comment by michelem09** [comment] 2017-11-03 14:45
This is really weird, I have other users telling me the same but I can't reproduce this at my side (with 3 different RPI model).
Could you give me more info, anything that could be different by my side.

**Comment by dyingphoenix** [comment] 2017-11-03 15:03
What I do:
Installing Image 2017-09-07-raspbian-stretch-lite.img
apt-get update && apt-get upgrade
reboot

uname -a output:
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

cat /proc/cpuinfo output:
Hardware        : BCM2835
Revision        : a02082

If you need anything else just tell me.

**Comment by michelem09** [comment] 2017-11-07 08:04
Please could you send me an email to support@getminera.com soI send back a link to test a new image?

**Comment by Chukman** [comment] 2017-11-09 18:08
The problem described here seems to fit my own. 

Trying to use raspberry pi B, plugged with ethernet cord, to run Minera 0.8.1: 
- loading Raspbian, the device _connected_ to the network just fine, 
- when using the minera image no connection may be established. 
-loopback is indeed active; eth0 port is _used_ yet no IP address is established
-tried manual install using the script on the github page and then the problem occurred again after reboot

My description of the issue seems to be exactly the same as dyingphoenixs and others. I hope this helps in resolving it, if you need more data from me just tell me as well.

**Comment by michelem09** [comment] 2017-11-09 18:09
Please could you send me an email to support@getminera.com so I send back a link to test a new image?

**Comment by michelem09** [comment] 2017-11-28 17:26
New image should fix this problem. Feel free to re-open.

**Closed by michelem09** 2017-11-28 17:26 UTC
